#!/bin/bash
pkg_name=${@: -1}

SCRIPT=$(greadlink -f "$0")
BASEDIR=$(dirname "$SCRIPT")
export PKG_CONFIG_PATH=${BASEDIR}/toolchain-android/lib/pkgconfig

echo BASEDIR ${BASEDIR}
echo PKG_CONFIG_PATH ${PKG_CONFIG_PATH}

echo ${PKG_CONFIG_PATH}
echo ##################
echo ##################
echo ##################
echo ##################

case $1 in
  --exists)
    pkg-config --exists $pkg_name
    ;;
  --cflags)
    echo $(pkg-config --cflags $pkg_name)
    ;;
  --libs)
    echo $(pkg-config --libs $pkg_name)
    ;;
  *)
    echo "FFmpeg pkg-config to build FFmpeg for Android!"
    ;;
esac
